### ISSUE TITLE
zoom functionality

### ISSUE THREAD

**Issue by blun** [jepler/cropgui#50] opened 2017-11-29 21:08 UTC
Please implement control elements (and/or command line options) to manually change the zoom ratio of the image display. And maybe another one for toggling some MCU block boundary visualization.
As it is, pixel-exact placement of a crop boundary takes a lot of trial and error or even resorting to jpegtran on the command line.

**Comment by nicolas-raoul** [comment] 2017-12-19 07:43
I think this is a duplicate of #5.
@blun how would this functionality differ from the functionality you requested at #5?

**Comment by StyXman** [comment] 2020-11-23 20:56
Yeah, I think this is a dupe of #5.

**Closed** 2023-09-23 15:59 UTC
Labels: help wanted
